export class ConnectorFakeData {
    public static data = [
        {
            'id': 1,
            'Project': 1,
            'Customer_PN': '6Q0 035 576',
            'TE_PN': '1452728-1',
            'Description': 'PLUG HOUSING CODE A BLACK, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code A',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 2,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 A',
            'TE_PN': '1452728-2',
            'Description': 'PLUG HOUSING CODE B CREAM, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code B',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 3,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 B',
            'TE_PN': '1452728-3',
            'Description': 'PLUG HOUSING CODE C BLUE, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code C',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 4,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 C',
            'TE_PN': '1452728-4',
            'Description': 'PLUG HOUSING CODE D CLARET VIOLETT, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code D',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 5,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 D',
            'TE_PN': '1452728-5',
            'Description': 'PLUG HOUSING CODE E GREEN, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code E',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 6,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 E',
            'TE_PN': '1452728-6',
            'Description': 'PLUG HOUSING CODE F BROWN, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Femalee Code F',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 7,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 F',
            'TE_PN': '1452728-7',
            'Description': 'PLUG HOUSING CODE G BLUE GREY, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Femal Code G',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 8,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 G',
            'TE_PN': '1452728-8',
            'Description': 'PLUG HOUSING CODE H VIOLETT, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code H',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 9,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 H',
            'TE_PN': '1452728-9',
            'Description': 'PLUG HOUSING CODE I BEIGE, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code I',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 10,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 J',
            'TE_PN': '1-1452728-0',
            'Description': 'PLUG HOUSING CODE K CURRY, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code K',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 11,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 K',
            'TE_PN': '1-1452728-1',
            'Description': 'PLUG HOUSING CODE Z WATER BLUE, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code Z',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 12,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 L',
            'TE_PN': '1-1452728-2',
            'Description': 'PLUG HOUSING CODE L CARMINE RED, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code L',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 13,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 M',
            'TE_PN': '1-1452728-3',
            'Description': 'PLUG HOUSING CODE M PASTEL ORANGE, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code M',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 14,
            'Project': 1,
            'Customer_PN': '6Q0 035 576 N',
            'TE_PN': '1-1452728-4',
            'Description': 'PLUG HOUSING CODE N PASTEL GREEN, 1WAY, FAKRA 2',
            'Rev': 'E',
            'Column1': '180 1P Female Code N',
            'Config_Connect': 1,
            'status': 'active'
        },
        {
            'id': 15,
            'Project': 1,
            'Customer_PN': '6Q0 035 575',
            'TE_PN': '1452727-1',
            'Description': 'JACK HOUSING CODE A BLACK, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code A',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 16,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 A',
            'TE_PN': '1452727-2',
            'Description': 'JACK HOUSING CODE B CREAM, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code B',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 17,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 B',
            'TE_PN': '1452727-3',
            'Description': 'JACK HOUSING CODE C BLUE, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code C',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 18,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 C',
            'TE_PN': '1452727-4',
            'Description': 'JACK HOUSING CODE D CLARET VIOLETT, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code D',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 19,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 D',
            'TE_PN': '1452727-5',
            'Description': 'JACK HOUSING CODE E GREEN, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code E',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 20,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 E',
            'TE_PN': '1452727-6',
            'Description': 'JACK HOUSING CODE F BROWN, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code F',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 21,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 F',
            'TE_PN': '1452727-7',
            'Description': 'JACK HOUSING CODE G BLUE GREY, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code G',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 22,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 G',
            'TE_PN': '1452727-8',
            'Description': 'JACK HOUSING CODE H VIOLETT, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code H',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 23,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 H',
            'TE_PN': '1452727-9',
            'Description': 'JACK HOUSING CODE I BEIGE, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code I',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 24,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 J',
            'TE_PN': '1-1452727-0',
            'Description': 'JACK HOUSING CODE K CURRY, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code K',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 25,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 K',
            'TE_PN': '1-1452727-1',
            'Description': 'JACK HOUSING CODE Z WATER BLUE, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code Z',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 26,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 L',
            'TE_PN': '1-1452727-2',
            'Description': 'JACK HOUSING CODE L CARMINE RED, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code L',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 27,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 M',
            'TE_PN': '1-1452727-3',
            'Description': 'JACK HOUSING CODE M PASTEL ORANGE, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code M',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 28,
            'Project': 1,
            'Customer_PN': '6Q0 035 575 N',
            'TE_PN': '1-1452727-4',
            'Description': 'JACK HOUSING CODE N PASTEL GREEN, 1WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 1P Male Code N',
            'Config_Connect': 2,
            'status': 'active'
        },
        {
            'id': 29,
            'Project': 1,
            'Customer_PN': '6Q0 035 671',
            'TE_PN': '1452725-1',
            'Description': 'JACK HOUSING CODE A BLACK, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code A',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 30,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 A',
            'TE_PN': '1452725-2',
            'Description': 'JACK HOUSING CODE B CREAM, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code B',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 31,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 B',
            'TE_PN': '1452725-3',
            'Description': 'JACK HOUSING CODE C BLUE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code C',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 32,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 C',
            'TE_PN': '1452725-4',
            'Description': 'JACK HOUSING CODE D CLARET VIOLETT, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code D',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 33,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 D',
            'TE_PN': '1452725-5',
            'Description': 'JACK HOUSING CODE E GREEN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code E',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 34,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 E',
            'TE_PN': '1452725-6',
            'Description': 'JACK HOUSING CODE F BROWN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code F',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 35,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 F',
            'TE_PN': '1452725-7',
            'Description': 'JACK HOUSING CODE G BLUE GREY, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code G',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 36,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 G',
            'TE_PN': '1452725-8',
            'Description': 'JACK HOUSING CODE H VIOLETT, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code H',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 37,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 H',
            'TE_PN': '1452725-9',
            'Description': 'JACK HOUSING CODE I BEIGE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code I',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 38,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 J',
            'TE_PN': '1-1452725-0',
            'Description': 'JACK HOUSING CODE K CURRY, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code K',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 39,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 K',
            'TE_PN': '1-1452725-1',
            'Description': 'JACK HOUSING CODE Z WATER BLUE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code Z',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 40,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 L',
            'TE_PN': '1-1452725-2',
            'Description': 'JACK HOUSING CODE L CARMINE RED, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code L',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 41,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 M',
            'TE_PN': '1-1452725-3',
            'Description': 'JACK HOUSING CODE M PASTEL ORANGE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code M',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 42,
            'Project': 1,
            'Customer_PN': '6Q0 035 671 N',
            'TE_PN': '1-1452725-4',
            'Description': 'JACK HOUSING CODE N PASTEL GREEN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Male Code N',
            'Config_Connect': 3,
            'status': 'active'
        },
        {
            'id': 43,
            'Project': 1,
            'Customer_PN': '6Q0 035 674',
            'TE_PN': '2236216-1',
            'Description': 'PLUG HSG ASSY CODE A BLACK, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code A',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 44,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 A',
            'TE_PN': '2236216-2',
            'Description': 'PLUG HSG ASSYCODE B CREAM, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code B',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 45,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 B',
            'TE_PN': '2236216-3',
            'Description': 'PLUG HSG ASSY CODE C BLUE, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code C',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 46,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 C',
            'TE_PN': '2236216-4',
            'Description': 'PLUG HSG ASSY CODE D CLARET VIOLETT, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code D',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 47,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 D',
            'TE_PN': '2236216-5',
            'Description': 'PLUG HSG ASSY CODE E GREEN, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code E',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 48,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 E',
            'TE_PN': '2236216-6',
            'Description': 'PLUG HSG ASSY CODE F BROWN, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code F',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 49,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 F',
            'TE_PN': '2236216-7',
            'Description': 'PLUG HSG ASSY CODE G BLUE GREY, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code G',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 50,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 G',
            'TE_PN': '2236216-8',
            'Description': 'PLUG HSG ASSY CODE H VIOLETT, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code H',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 51,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 H',
            'TE_PN': '2236216-9',
            'Description': 'PLUG HSG ASSY CODE I BEIGE, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code I',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 52,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 J',
            'TE_PN': '1-2236216-0',
            'Description': 'PLUG HSG ASSY CODE K CURRY, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code K',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 53,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 K',
            'TE_PN': '1-2236216-1',
            'Description': 'PLUG HSG ASSY CODE Z WATER BLUE, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code Z',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 54,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 L',
            'TE_PN': '1-2236216-2',
            'Description': 'PLUG HSG ASSY CODE L CARMINE RED, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code L',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 55,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 M',
            'TE_PN': '1-2236216-3',
            'Description': 'PLUG HSG ASSY CODE M PASTEL ORANGE, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code M',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 56,
            'Project': 1,
            'Customer_PN': '6Q0 035 674 N',
            'TE_PN': '1-2236216-4',
            'Description': 'PLUG HSG ASSY CODE N PASTEL GREEN, 1WAY, 90 DEG, FAKRA 2',
            'Rev': 'A1',
            'Column1': '90 1POS Code N',
            'Config_Connect': 4,
            'status': 'active'
        },
        {
            'id': 57,
            'Project': 1,
            'Customer_PN': '6Q0 035 675',
            'TE_PN': '2236187-1',
            'Description': 'PLUG HSG ASSY CODE A BLACK, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code A',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 58,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 A',
            'TE_PN': '2236187-2',
            'Description': 'PLUG HSG ASSYCODE B CREAM, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code B',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 59,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 B',
            'TE_PN': '2236187-3',
            'Description': 'PLUG HSG ASSY CODE C BLUE, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code C',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 60,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 C',
            'TE_PN': '2236187-4',
            'Description': 'PLUG HSG ASSY CODE D CLARET VIOLETT, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code D',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 61,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 D',
            'TE_PN': '2236187-5',
            'Description': 'PLUG HSG ASSY CODE E GREEN, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code E',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 62,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 E',
            'TE_PN': '2236187-6',
            'Description': 'PLUG HSG ASSY CODE F BROWN, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code F',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 63,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 F',
            'TE_PN': '2236187-7',
            'Description': 'PLUG HSG ASSY CODE G BLUE GREY, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code G',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 64,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 G',
            'TE_PN': '2236187-8',
            'Description': 'PLUG HSG ASSY CODE H VIOLETT, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code H',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 65,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 H',
            'TE_PN': '2236187-9',
            'Description': 'PLUG HSG ASSY CODE I BEIGE, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code I',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 66,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 J',
            'TE_PN': '1-2236187-0',
            'Description': 'PLUG HSG ASSY CODE K CURRY, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code K',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 67,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 K',
            'TE_PN': '1-2236187-1',
            'Description': 'PLUG HSG ASSY CODE Z WATER BLUE, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code Z',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 68,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 L',
            'TE_PN': '1-2236187-2',
            'Description': 'PLUG HSG ASSY CODE L CARMINE RED, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code L',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 69,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 M',
            'TE_PN': '1-2236187-3',
            'Description': 'PLUG HSG ASSY CODE M PASTEL ORANGE, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code M',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 70,
            'Project': 1,
            'Customer_PN': '6Q0 035 675 N',
            'TE_PN': '1-2236187-4',
            'Description': 'PLUG HSG ASSY CODE N PASTEL GREEN, 2WAY, 90 DEG, FAKRA 2',
            'Rev': 'A',
            'Column1': '90 2POS Code N',
            'Config_Connect': 5,
            'status': 'active'
        },
        {
            'id': 71,
            'Project': 1,
            'Customer_PN': '4L0 035 576',
            'TE_PN': '2112226-1',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE A, BLACK',
            'Rev': 'A',
            'Column1': 'Sealed Female TUBE Code A',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 72,
            'Project': 1,
            'Customer_PN': '4L0 035 576 A',
            'TE_PN': '2112226-2',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE B, WHITE',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code B',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 73,
            'Project': 1,
            'Customer_PN': '4L0 035 576 B',
            'TE_PN': '2112226-3',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE C, BLUE',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code C',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 74,
            'Project': 1,
            'Customer_PN': '4L0 035 576 C',
            'TE_PN': '2112226-4',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE D, BORDEAUX',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code D',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 75,
            'Project': 1,
            'Customer_PN': '4L0 035 576 D',
            'TE_PN': '2112226-5',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE E, GREEN',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code E',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 76,
            'Project': 1,
            'Customer_PN': '4L0 035 576 E',
            'TE_PN': '2112226-6',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE F, BROWN',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code F',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 77,
            'Project': 1,
            'Customer_PN': '4L0 035 576 F',
            'TE_PN': '2112226-7',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE G, GREY',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code G',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 78,
            'Project': 1,
            'Customer_PN': '4L0 035 576 G',
            'TE_PN': '2112226-8',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE H, VIOLET',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code H',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 79,
            'Project': 1,
            'Customer_PN': '4L0 035 576 H',
            'TE_PN': '2112226-9',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE I, BEIGE',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code I',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 80,
            'Project': 1,
            'Customer_PN': '4L0 035 576 I',
            'TE_PN': '1-2112226-0',
            'Description': 'FAKRA II, PLUG HSG, VW, SEALED, TUBE CODE K, CURRY',
            'Rev': 'A',
            'Column1': 'Sealed  Female TUBE  Code K',
            'Config_Connect': 6,
            'status': 'active'
        },
        {
            'id': 81,
            'Project': 1,
            'Customer_PN': '420 035 575',
            'TE_PN': '2295797-1',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE A, BLACK',
            'Rev': 'A',
            'Column1': 'Sealed male  Code A',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 82,
            'Project': 1,
            'Customer_PN': '420 035 575 A',
            'TE_PN': '2295797-2',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE B, WHITE',
            'Rev': 'A',
            'Column1': 'Sealed male  Code B',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 83,
            'Project': 1,
            'Customer_PN': '420 035 575 B',
            'TE_PN': '2295797-3',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE C, BLUE',
            'Rev': 'A',
            'Column1': 'Sealed male  Code C',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 84,
            'Project': 1,
            'Customer_PN': '420 035 575 C',
            'TE_PN': '2295797-4',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE D, BORDEAUX',
            'Rev': 'A',
            'Column1': 'Sealed male  Code D',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 85,
            'Project': 1,
            'Customer_PN': '420 035 575 D',
            'TE_PN': '2295797-5',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE E, GREEN',
            'Rev': 'A',
            'Column1': 'Sealed male  Code E',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 86,
            'Project': 1,
            'Customer_PN': '420 035 575 E',
            'TE_PN': '2295797-6',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE F, BROWN',
            'Rev': 'A',
            'Column1': 'Sealed male  Code F',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 87,
            'Project': 1,
            'Customer_PN': '420 035 575 F',
            'TE_PN': '2295797-7',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE G, GREY',
            'Rev': 'A',
            'Column1': 'Sealed male  Code G',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 88,
            'Project': 1,
            'Customer_PN': '420 035 575 G',
            'TE_PN': '2295797-8',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE H, VIOLET',
            'Rev': 'A',
            'Column1': 'Sealed male  Code H',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 89,
            'Project': 1,
            'Customer_PN': '420 035 575 H',
            'TE_PN': '2295797-9',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE I, BEIGE',
            'Rev': 'A',
            'Column1': 'Sealed male  Code I',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 90,
            'Project': 1,
            'Customer_PN': '420 035 575 J',
            'TE_PN': '1-2295797-0',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE CODE K, CURRY',
            'Rev': 'A',
            'Column1': 'Sealed male  Code K',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 91,
            'Project': 1,
            'Customer_PN': '420 035 575 K',
            'TE_PN': '1-2295797-1',
            'Description': 'FAKRA II, JACK HSG, VW, SEALED, TUBE\nCODE Z, WATERBLUE',
            'Rev': 'A',
            'Column1': 'Sealed male  Code Z',
            'Config_Connect': 7,
            'status': 'active'
        },
        {
            'id': 92,
            'Project': 1,
            'Customer_PN': '4N0 035 674',
            'TE_PN': '2331774-1',
            'Description': 'A FAKRA II, PLUG HSG. 90, SEALED, CODE A, BLACK',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE A',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 93,
            'Project': 1,
            'Customer_PN': '4N0 035 674 A',
            'TE_PN': '2331774-2',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE B, WHITE',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE B',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 94,
            'Project': 1,
            'Customer_PN': '4N0 035 674 B',
            'TE_PN': '2331774-3',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE C, BLUE',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE C',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 95,
            'Project': 1,
            'Customer_PN': '4N0 035 674 C',
            'TE_PN': '2331774-4',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE D, PURPLE',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE D',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 96,
            'Project': 1,
            'Customer_PN': '4N0 035 674 D',
            'TE_PN': '2331774-5',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE E, GREEN',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE E',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 97,
            'Project': 1,
            'Customer_PN': '4N0 035 674 E',
            'TE_PN': '2331774-6',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE F, BROWN',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE F',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 98,
            'Project': 1,
            'Customer_PN': '4N0 035 674 K',
            'TE_PN': '1-2331774-0',
            'Description': 'FAKRA II, PLUG HSG. 90, SEALED, CODE K, CURRY',
            'Rev': 'A',
            'Column1': 'PLUG HSG. 90, SEALED, CODE K',
            'Config_Connect': 8,
            'status': 'active'
        },
        {
            'id': 99,
            'Project': 1,
            'Customer_PN': '7L0 035 608',
            'TE_PN': '1452726-1',
            'Description': 'PLUG HOUSING CODE A BLACK, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code A',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 100,
            'Project': 1,
            'Customer_PN': '7L0 035 608 A',
            'TE_PN': '1452726-2',
            'Description': 'PLUG HOUSING CODE B CREAM, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code B',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 101,
            'Project': 1,
            'Customer_PN': '7L0 035 608 B',
            'TE_PN': '1452726-3',
            'Description': 'PLUG HOUSING CODE C BLUE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code C',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 102,
            'Project': 1,
            'Customer_PN': '7L0 035 608 C',
            'TE_PN': '1452726-4',
            'Description': 'PLUG HOUSING CODE D CLARET VIOLETT, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code D',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 103,
            'Project': 1,
            'Customer_PN': '7L0 035 608 D',
            'TE_PN': '1452726-5',
            'Description': 'PLUG HOUSING CODE E GREEN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code E',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 104,
            'Project': 1,
            'Customer_PN': '7L0 035 608 E',
            'TE_PN': '1452726-6',
            'Description': 'PLUG HOUSING CODE F BROWN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code F',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 105,
            'Project': 1,
            'Customer_PN': '7L0 035 608 F',
            'TE_PN': '1452726-7',
            'Description': 'PLUG HOUSING CODE G BLUE GREY, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code G',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 106,
            'Project': 1,
            'Customer_PN': '7L0 035 608 G',
            'TE_PN': '1452726-8',
            'Description': 'PLUG HOUSING CODE H VIOLETT, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code H',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 107,
            'Project': 1,
            'Customer_PN': '7L0 035 608 H',
            'TE_PN': '1452726-9',
            'Description': 'PLUG HOUSING CODE I BEIGE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code I',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 108,
            'Project': 1,
            'Customer_PN': '7L0 035 608 J',
            'TE_PN': '1-1452726-0',
            'Description': 'PLUG HOUSING CODE K CURRY, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code K',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 109,
            'Project': 1,
            'Customer_PN': '7L0 035 608 K',
            'TE_PN': '1-1452726-1',
            'Description': 'PLUG HOUSING CODE Z WATER BLUE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code Z',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 110,
            'Project': 1,
            'Customer_PN': '7L0 035 608 L',
            'TE_PN': '1-1452726-2',
            'Description': 'PLUG HOUSING CODE L CARMINE RED, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code L',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 111,
            'Project': 1,
            'Customer_PN': '7L0 035 608 M',
            'TE_PN': '1-1452726-3',
            'Description': 'PLUG HOUSING CODE M PASTEL ORANGE, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code M',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 112,
            'Project': 1,
            'Customer_PN': '7L0 035 608 N',
            'TE_PN': '1-1452726-4',
            'Description': 'PLUG HOUSING CODE N PASTEL GREEN, 2WAY, FAKRA 2',
            'Rev': 'B',
            'Column1': '180 2P Female Code N',
            'Config_Connect': 9,
            'status': 'active'
        },
        {
            'id': 113,
            'Project': 1,
            'Customer_PN': '6Q0 035 608',
            'TE_PN': '2-1452726-1',
            'Description': 'PLUG HOUSING CODE A BLACK, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code A',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 114,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 A',
            'TE_PN': '2-1452726-2',
            'Description': 'PLUG HOUSING CODE B CREAM, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code B',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 115,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 B',
            'TE_PN': '2-1452726-3',
            'Description': 'PLUG HOUSING CODE C BLUE, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code C',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 116,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 C',
            'TE_PN': '2-1452726-4',
            'Description': 'PLUG HOUSING CODE D CLARET VIOLETT, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code D',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 117,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 D',
            'TE_PN': '2-1452726-5',
            'Description': 'PLUG HOUSING CODE E GREEN, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code E',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 118,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 E',
            'TE_PN': '2-1452726-6',
            'Description': 'PLUG HOUSING CODE F BROWN, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code F',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 119,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 F',
            'TE_PN': '2-1452726-7',
            'Description': 'PLUG HOUSING CODE G BLUE GREY, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code G',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 120,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 G',
            'TE_PN': '2-1452726-8',
            'Description': 'PLUG HOUSING CODE H VIOLETT, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code H',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 121,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 H',
            'TE_PN': '2-1452726-9',
            'Description': 'PLUG HOUSING CODE I BEIGE, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code I',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 122,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 J',
            'TE_PN': '3-1452726-0',
            'Description': 'PLUG HOUSING CODE K CURRY, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code K',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 123,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 K',
            'TE_PN': '3-1452726-1',
            'Description': 'PLUG HOUSING CODE Z WATER BLUE, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code Z',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 124,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 L',
            'TE_PN': '3-1452726-2',
            'Description': 'PLUG HOUSING CODE L CARMINE RED, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code L',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 125,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 M',
            'TE_PN': '3-1452726-3',
            'Description': 'PLUG HOUSING CODE M PASTEL ORANGE, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code M',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 126,
            'Project': 1,
            'Customer_PN': '6Q0 035 608 N',
            'TE_PN': '3-1452726-4',
            'Description': 'PLUG HOUSING CODE N PASTEL GREEN, 2WAY, FAKRA 2, WITH MOUNT',
            'Rev': 'B',
            'Column1': '180 2P Female With Mount Code N',
            'Config_Connect': 10,
            'status': 'active'
        },
        {
            'id': 127,
            'Project': 1,
            'Customer_PN': '5QF 035 576',
            'TE_PN': '2339595-1',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE A, BLACK',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD A',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 128,
            'Project': 1,
            'Customer_PN': '5QF 035 576 A',
            'TE_PN': '2339595-2',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE B, WHITE',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD B',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 129,
            'Project': 1,
            'Customer_PN': '5QF 035 576 B',
            'TE_PN': '2339595-3',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED,CODE C, BLUE',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD C',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 130,
            'Project': 1,
            'Customer_PN': '5QF 035 576 C',
            'TE_PN': '2339595-4',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE D, BORDEAUX VIOLET',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD D',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 131,
            'Project': 1,
            'Customer_PN': '5QF 035 576 D',
            'TE_PN': '2339595-5',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE E,GREEN',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD E',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 132,
            'Project': 1,
            'Customer_PN': '5QF 035 576 E',
            'TE_PN': '2339595-6',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE F,BROWN',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD F',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 133,
            'Project': 1,
            'Customer_PN': '5QF 035 576 F',
            'TE_PN': '2339595-7',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE G,GREY',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD G',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 134,
            'Project': 1,
            'Customer_PN': '5QF 035 576 G',
            'TE_PN': '2339595-8',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE H,VIOLET',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD H',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 135,
            'Project': 1,
            'Customer_PN': '5QF 035 576 H',
            'TE_PN': '2339595-9',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE I,BEIG',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD I',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 136,
            'Project': 1,
            'Customer_PN': '5QF 035 576 J',
            'TE_PN': '1-2339595-0',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE K,CURRY',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD K',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 137,
            'Project': 1,
            'Customer_PN': '5QF 035 576 K',
            'TE_PN': '1-2339595-1',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE Z,WATERBLUE',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD Z',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 138,
            'Project': 1,
            'Customer_PN': '5QF 035 576 L',
            'TE_PN': '1-2339595-2',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALEDCODE L, CARMINE RED',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD L',
            'Config_Connect': 11,
            'status': 'active'
        },
        {
            'id': 139,
            'Project': 1,
            'Customer_PN': '5QF 035 576 N',
            'TE_PN': '1-2339595-4',
            'Description': 'FAKRA PLUG HSG, ROSENBERGER 180 DEGREE SEALED, CODE N,PASTEL GREEN',
            'Rev': 'A',
            'Column1': 'FAKRA PLUG HSG SEALED, COD N',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 140,
            'Project': 1,
            'Customer_PN': '4N0 035 576',
            'TE_PN': '2310886-1',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE A , JET BLACK',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE A',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 141,
            'Project': 1,
            'Customer_PN': '4N0 035 576 A',
            'TE_PN': '2310886-2',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE B , PURE WHITE',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE B',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 142,
            'Project': 1,
            'Customer_PN': '4N0 035 576 B',
            'TE_PN': '2310886-3',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE C, LIGHT BLUE',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE C',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 143,
            'Project': 1,
            'Customer_PN': '4N0 035 576 C',
            'TE_PN': '2310886-4',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE D, CLARET VIOLET',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE D',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 144,
            'Project': 1,
            'Customer_PN': '4N0 035 576 D',
            'TE_PN': '2310886-5',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE E, GREEN',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE E',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 145,
            'Project': 1,
            'Customer_PN': '4N0 035 576 E',
            'TE_PN': '2310886-6',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE F, NUT BROWN',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE F',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 146,
            'Project': 1,
            'Customer_PN': '4N0 035 576 F',
            'TE_PN': '2310886-9',
            'Description': '4POS, MATE-AX, REC. HSG ASSY,180DEG CODE Z, WATER BLUE',
            'Rev': 'C',
            'Column1': 'MATE-AX CODE Z',
            'Config_Connect': 12,
            'status': 'active'
        },
        {
            'id': 147,
            'Project': 1,
            'Customer_PN': '5QF 035 575',
            'TE_PN': '2358340-1',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE A, BLACK',
            'Rev': 'A',
            'Column1': 'FAKRA JACK HSG SEALED, COD A',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 148,
            'Project': 1,
            'Customer_PN': '5QF 035 575 A',
            'TE_PN': '2358340-2',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE B, WHITE',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD B',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 149,
            'Project': 1,
            'Customer_PN': '5QF 035 575 B',
            'TE_PN': '2358340-3',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE C, BLUE',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD C',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 150,
            'Project': 1,
            'Customer_PN': '5QF 035 575 C',
            'TE_PN': '2358340-4',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE D, BORDEUX VIOLET',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD D',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 151,
            'Project': 1,
            'Customer_PN': '5QF 035 575 D',
            'TE_PN': '2358340-5',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE E, green',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD E',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 152,
            'Project': 1,
            'Customer_PN': '5QF 035 575 E',
            'TE_PN': '2358340-6',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE F, brown',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD F',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 153,
            'Project': 1,
            'Customer_PN': '5QF 035 575 F',
            'TE_PN': '2358340-7',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE G, grey',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD G',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 154,
            'Project': 1,
            'Customer_PN': '5QF 035 575 G',
            'TE_PN': '2358340-8',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE H, violet',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD H',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 155,
            'Project': 1,
            'Customer_PN': '5QF 035 575 H',
            'TE_PN': '2358340-9',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE I, beige',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD I',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 156,
            'Project': 1,
            'Customer_PN': '5QF 035 575 J',
            'TE_PN': '1-2358340-0',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE K, curry',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD K',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 157,
            'Project': 1,
            'Customer_PN': '5QF 035 575 K',
            'TE_PN': '1-2358340-1',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE Z, water blue',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD Z',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 158,
            'Project': 1,
            'Customer_PN': '5QF 035 575 L',
            'TE_PN': '1-2358340-2',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE L, carmine red',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD L',
            'Config_Connect': 13,
            'status': 'active'
        },
        {
            'id': 159,
            'Project': 1,
            'Customer_PN': '5QF 035 575 N',
            'TE_PN': '1-2358340-4',
            'Description': 'FAKRA JACk HSG VW, Rosenberger 180 Degree SEALED, CODE N, pastel green',
            'Rev': 'A',
            'Column1': 'FAKRA JACK  HSG SEALED, COD N',
            'Config_Connect': 13,
            'status': 'active'
        }
    ];
}
