export class HarnessFakeData {
  public static data = [
    {
      'id': 1,
      'name': 'DRX',
      'Manufacturing_Code': 'DRX PART NO. (8 DIGITS), TE PART NO. AND CURRENT REV.<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER<br> LEVEL (9 DIGITS),DATE CODE (DCWYS).<br>(D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br> DRX PART NO. AND TE PART NO. SEE TABLE.<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'FXXXXXXX X-XXX-X/XXDCWYS',
      'status': 'active'
    },
    {
      'id': 2,
      'name': 'SEBN',
      'Manufacturing_Code': 'SEBN PN (9 DIGITS) SESAM PN (8 DIGITS) .<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER<br>DATE CODE (DCWYS)<br>    (D: DAY, 1=SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>    SEBN PART NO., SESAM PART NO. SEE TABLE.<br>    MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'XXXXXXXXX XXXXXX-XXDCWYS',
      'status': 'active'
    },
    {
      'id': 3,
      'name': 'LEON',
      'Manufacturing_Code': 'LEONI PART NO. (9 DIGITS). PRINTED WITHOUT "00" FOR<br>PROTOTYPE.<br>TE PART NO, AND CURRENT REV. (7 DIGITS).<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER. DATE<br>CODE DCWYS ,<br>(D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF<br>YEAR; S:SHIFT).<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL<br>ELECTRICAL TEST.',
      'BARE_CODE': 'PXXXXXXXX XXX-X/XXDCWYS',
      'status': 'active'
    },
    {
      'id': 4,
      'name': 'KROS',
      'Manufacturing_Code': 'SUPPLIER CODE, 3 LAST DIGITS OF TE PART NO-X . AND CURRENT REV.LEVEL (TEX-XXX-X/X).<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER<br>DATE CODE (DCWYS), KROSCHU PART NO.<br>(D: DAY, 1=SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>KROSCHU PART NO., TE PART NO. SEE TABLE.<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST.',
      'BARE_CODE': 'TEXXX-X/XXDCWYS XXXXXXXX',
      'status': 'active'
    },
    {
      'id': 5,
      'name': 'FUJI',
      'Manufacturing_Code': 'FUJIKURA PART NO. (7 DIGITS), TE PART NO. AND CURRENT REV. (9 DIGITS),<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER<br>    DATE CODE (DCWYS).<br>    (D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>    FUJIKURA PART NO. AND TE PART NO. SEE TABLE.<br>    MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST <br>    PERMANENTLY TO THE CABLE BY USING THERMOFOIL PRINTER EQUIPPED <br>    WITH YELLOW FOIL..',
      'BARE_CODE': 'AFXXXXX X-XXX-X/XXDCWYS',
      'status': 'active'
    },
    {
      'id': 6,
      'name': 'Aptiv',
      'Manufacturing_Code': 'APTIV PART NO._TE PART NO._REV._DATE CODE (DCWYYS).<br>(D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'XXXXXXXX_XXXXXXX-X_R_DCWYYS',
      'status': 'active'
    },
    {
      'id': 7,
      'name': 'Ford',
      'Manufacturing_Code': 'LABEL TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST: PRODUCTION DATE: YEAR,M ONTH,<br>DAY, SHIFT (YYYYMMDDS). PRODUCTION LOCATION: 5 LETTER CODE OF THE PRODUCTION PLANT.<br>BARCODE - TYPE 128B: FORD PN. 2D CODE (DATAMATRIX) - OPTIONAL, CONTENT ACC.<br>PRODUCTION PLANT REQUIREMENTS. ALTERNATIVELY,<br>LABEL 1832423-1 CAN BE USED INSTEAD OF LABEL 5-1768419',
      'BARE_CODE': '',
      'status': 'active'
    },
    {
      'id': 8,
      'name': 'Lear',
      'Manufacturing_Code': 'TE PART NO. AND CURRENT REV. LEVEL (9DIGITS). DATE CODE (DCWYS)<br>(D: DAY, 1= SUNDAY ; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S :SHIFT<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'XXXXXXX-X/X DCWYS',
      'status': 'active'
    },
    {
      'id': 9,
      'name': 'FICO',
      'Manufacturing_Code': 'FICO PART NO. (9 DIGITS), TE PART NO. AND CURRENT REV.<br>LINE NUMBER (X): CAN BE NUMBER, LETTER OR CHARACTER<br> LEVEL (9 DIGITS),DATE CODE (DCWYS).<br>(D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>FICO PART NO. AND TE PART NO. SEE TABLE.<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'FXXXXXXX X-XXX-X/XXDCWYS',
      'status': 'active'
    },
    {
      'id': 10,
      'name': 'COFA',
      'Manufacturing_Code': 'THE LAST 7 DIGITS OF COFAT PART NO_TE PART NO_DATE CODE (DCWYYS).(D: DAY, 1= SUNDAY; CW: CALENDER WEEK; Y: LAST DIGIT OF YEAR; S: SHIFT).<br>COFAT PART NO. AND TE PART NO. SEE TABLE.<br>MANUFACTURING CODE TO BE APPLIED AFTER SUCCESSFUL ELECTRICAL TEST',
      'BARE_CODE': 'XXXXXXX_X-XXXXXX-X_DCWYS',
      'status': 'active'
    }
  ];
}
